In [1]:
import math
import numpy as np
import torch
from torch import nn
from d2l import torch as d2l

In [2]:
max_degree = 20
n_train, n_test = 100, 100
true_w = np.zeros(max_degree)
true_w[0:4] = np.array([5, 1.2, -3.4, 5.6])

In [13]:
features = np.random.normal(size=(n_train + n_test, 1))
np.random.shuffle(features)
poly_features = np.power(features, np.arange(max_degree).reshape(1, -1))
for i in range(max_degree):
    poly_features[:, i] /= math.gamma(i+1)
labels = np.dot(poly_features, true_w)
labels += np.random.normal(scale=.1, size=labels.shape)

In [14]:
true_w, features, poly_features, labels = [ torch.tensor(x, dtype=torch.float32) for x in [true_w, features, poly_features, labels]]
features[:2], poly_features[:2, :], labels[:2]

(tensor([[-0.5660],
         [ 0.4185]]),
 tensor([[ 1.0000e+00, -5.6600e-01,  1.6018e-01, -3.0220e-02,  4.2762e-03,
          -4.8406e-04,  4.5663e-05, -3.6922e-06,  2.6122e-07, -1.6428e-08,
           9.2983e-10, -4.7844e-11,  2.2566e-12, -9.8250e-14,  3.9721e-15,
          -1.4988e-16,  5.3021e-18, -1.7653e-19,  5.5508e-21, -1.6536e-22],
         [ 1.0000e+00,  4.1847e-01,  8.7557e-02,  1.2213e-02,  1.2777e-03,
           1.0693e-04,  7.4581e-06,  4.4585e-07,  2.3322e-08,  1.0844e-09,
           4.5377e-11,  1.7263e-12,  6.0198e-14,  1.9378e-15,  5.7921e-17,
           1.6159e-18,  4.2261e-20,  1.0403e-21,  2.4185e-23,  5.3266e-25]]),
 tensor([3.6224, 5.4129]))

In [2]:
%matplotlib inline
import numpy as np
import pandas as pd
import torch
from torch import nn
from d2l import torch as d2l

In [4]:
import hashlib
import os
import tarfile
import zipfile
import requests

#@save
DATA_HUB = dict()
DATA_URL = 'http://d2l-data.s3-accelerate.amazonaws.com/'

In [5]:
def download(name, cache_dir=os.path.join('..', 'data')):  #@save
    """下载一个DATA_HUB中的文件，返回本地文件名。"""
    assert name in DATA_HUB, f"{name} 不存在于 {DATA_HUB}."
    url, sha1_hash = DATA_HUB[name]
    os.makedirs(cache_dir, exist_ok=True)
    fname = os.path.join(cache_dir, url.split('/')[-1])
    if os.path.exists(fname):
        sha1 = hashlib.sha1()
        with open(fname, 'rb') as f:
            while True:
                data = f.read(1048576)
                if not data:
                    break
                sha1.update(data)
        if sha1.hexdigest() == sha1_hash:
            return fname  # Hit cache
    print(f'正在从{url}下载{fname}...')
    r = requests.get(url, stream=True, verify=True)
    with open(fname, 'wb') as f:
        f.write(r.content)
    return fname

In [6]:
def download_extract(name, folder=None):  #@save
    """下载并解压zip/tar文件。"""
    fname = download(name)
    base_dir = os.path.dirname(fname)
    data_dir, ext = os.path.splitext(fname)
    if ext == '.zip':
        fp = zipfile.ZipFile(fname, 'r')
    elif ext in ('.tar', '.gz'):
        fp = tarfile.open(fname, 'r')
    else:
        assert False, '只有zip/tar文件可以被解压缩。'
    fp.extractall(base_dir)
    return os.path.join(base_dir, folder) if folder else data_dir

def download_all():  #@save
    """下载DATA_HUB中的所有文件。"""
    for name in DATA_HUB:
        download(name)

In [7]:
DATA_HUB['kaggle_house_train'] = (  #@save
    DATA_URL + 'kaggle_house_pred_train.csv',
    '585e9cc93e70b39160e7921475f9bcd7d31219ce')

DATA_HUB['kaggle_house_test'] = (  #@save
    DATA_URL + 'kaggle_house_pred_test.csv',
    'fa19780a7b011d9b009e8bff8e99922a8ee2eb90')

In [8]:
train_data = pd.read_csv(download('kaggle_house_train'))
test_data = pd.read_csv(download('kaggle_house_test'))

正在从http://d2l-data.s3-accelerate.amazonaws.com/kaggle_house_pred_train.csv下载../data/kaggle_house_pred_train.csv...
正在从http://d2l-data.s3-accelerate.amazonaws.com/kaggle_house_pred_test.csv下载../data/kaggle_house_pred_test.csv...


In [9]:
print(train_data.shape)
print(test_data.shape)

(1460, 81)
(1459, 80)


In [10]:
print(train_data.iloc[0:4, [0, 1, 2, 3, -3, -2, -1]])

   Id  MSSubClass MSZoning  LotFrontage SaleType SaleCondition  SalePrice
0   1          60       RL         65.0       WD        Normal     208500
1   2          20       RL         80.0       WD        Normal     181500
2   3          60       RL         68.0       WD        Normal     223500
3   4          70       RL         60.0       WD       Abnorml     140000


In [12]:
all_features = pd.concat((train_data.iloc[:, 1:-1], test_data.iloc[:, 1:]))
all_features

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0             60       RL         65.0     8450   Pave   NaN      Reg   
1             20       RL         80.0     9600   Pave   NaN      Reg   
2             60       RL         68.0    11250   Pave   NaN      IR1   
3             70       RL         60.0     9550   Pave   NaN      IR1   
4             60       RL         84.0    14260   Pave   NaN      IR1   
...          ...      ...          ...      ...    ...   ...      ...   
1454         160       RM         21.0     1936   Pave   NaN      Reg   
1455         160       RM         21.0     1894   Pave   NaN      Reg   
1456          20       RL        160.0    20000   Pave   NaN      Reg   
1457          85       RL         62.0    10441   Pave   NaN      Reg   
1458          60       RL         74.0     9627   Pave   NaN      Reg   

     LandContour Utilities LotConfig  ... ScreenPorch PoolArea PoolQC  Fence  \
0            Lvl    AllPub    Inside  ...           0        0    NaN    NaN   
1            Lvl    AllPub       FR2  ...           0        0    NaN    NaN   
2            Lvl    AllPub    Inside  ...           0        0    NaN    NaN   
3            Lvl    AllPub    Corner  ...           0        0    NaN    NaN   
4            Lvl    AllPub       FR2  ...           0        0    NaN    NaN   
...          ...       ...       ...  ...         ...      ...    ...    ...   
1454         Lvl    AllPub    Inside  ...           0        0    NaN    NaN   
1455         Lvl    AllPub    Inside  ...           0        0    NaN    NaN   
1456         Lvl    AllPub    Inside  ...           0        0    NaN    NaN   
1457         Lvl    AllPub    Inside  ...           0        0    NaN  MnPrv   
1458         Lvl    AllPub    Inside  ...           0        0    NaN    NaN   

     MiscFeature MiscVal  MoSold  YrSold  SaleType  SaleCondition  
0            NaN       0       2    2008        WD         Normal  
1            NaN       0       5    2007        WD         Normal  
2            NaN       0       9    2008        WD         Normal  
3            NaN       0       2    2006        WD        Abnorml  
4            NaN       0      12    2008        WD         Normal  
...          ...     ...     ...     ...       ...            ...  
1454         NaN       0       6    2006        WD         Normal  
1455         NaN       0       4    2006        WD        Abnorml  
1456         NaN       0       9    2006        WD        Abnorml  
1457        Shed     700       7    2006        WD         Normal  
1458         NaN       0      11    2006        WD         Normal  

[2919 rows x 79 columns]

In [20]:
numeric_features = all_features.dtypes[all_features.dtypes != 'object'].index
all_features[numeric_features] = all_features[numeric_features].apply(
    lambda x: (x - x.mean()) / (x.std()))
# 在标准化数据之后，所有数据都意味着消失，因此我们可以将缺失值设置为0
all_features[numeric_features] = all_features[numeric_features].fillna(0)
all_features

MSSubClass  LotFrontage   LotArea  OverallQual  OverallCond  YearBuilt  \
0       0.067320    -0.202033 -0.217841     0.646073    -0.507197   1.046078   
1      -0.873466     0.501785 -0.072032    -0.063174     2.187904   0.154737   
2       0.067320    -0.061269  0.137173     0.646073    -0.507197   0.980053   
3       0.302516    -0.436639 -0.078371     0.646073    -0.507197  -1.859033   
4       0.067320     0.689469  0.518814     1.355319    -0.507197   0.947040   
...          ...          ...       ...          ...          ...        ...   
1454    2.419286    -2.266564 -1.043758    -1.481667     1.289537  -0.043338   
1455    2.419286    -2.266564 -1.049083    -1.481667    -0.507197  -0.043338   
1456   -0.873466     4.255477  1.246594    -0.772420     1.289537  -0.373465   
1457    0.655311    -0.342796  0.034599    -0.772420    -0.507197   0.682939   
1458    0.067320     0.220258 -0.068608     0.646073    -0.507197   0.715952   

      YearRemodAdd  MasVnrArea  BsmtFinSF1  BsmtFinSF2  ...  SaleType_Oth  \
0         0.896679    0.525112    0.580807    -0.29308  ...     -0.049021   
1        -0.395536   -0.572152    1.177910    -0.29308  ...     -0.049021   
2         0.848819    0.334770    0.097856    -0.29308  ...     -0.049021   
3        -0.682695   -0.572152   -0.494856    -0.29308  ...     -0.049021   
4         0.753100    1.387248    0.468851    -0.29308  ...     -0.049021   
...            ...         ...         ...         ...  ...           ...   
1454     -0.682695   -0.572152   -0.969026    -0.29308  ...     -0.049021   
1455     -0.682695   -0.572152   -0.415828    -0.29308  ...     -0.049021   
1456      0.561660   -0.572152    1.717937    -0.29308  ...     -0.049021   
1457      0.370221   -0.572152   -0.229233    -0.29308  ...     -0.049021   
1458      0.465941   -0.045913    0.694959    -0.29308  ...     -0.049021   

      SaleType_WD  SaleType_nan  SaleCondition_Abnorml  SaleCondition_AdjLand  \
0        0.394951     -0.018509              -0.263816              -0.064238   
1        0.394951     -0.018509              -0.263816              -0.064238   
2        0.394951     -0.018509              -0.263816              -0.064238   
3        0.394951     -0.018509               3.789226              -0.064238   
4        0.394951     -0.018509              -0.263816              -0.064238   
...           ...           ...                    ...                    ...   
1454     0.394951     -0.018509              -0.263816              -0.064238   
1455     0.394951     -0.018509               3.789226              -0.064238   
1456     0.394951     -0.018509               3.789226              -0.064238   
1457     0.394951     -0.018509              -0.263816              -0.064238   
1458     0.394951     -0.018509              -0.263816              -0.064238   

      SaleCondition_Alloca  SaleCondition_Family  SaleCondition_Normal  \
0                -0.091035             -0.126513              0.463857   
1                -0.091035             -0.126513              0.463857   
2                -0.091035             -0.126513              0.463857   
3                -0.091035             -0.126513             -2.155097   
4                -0.091035             -0.126513              0.463857   
...                    ...                   ...                   ...   
1454             -0.091035             -0.126513              0.463857   
1455             -0.091035             -0.126513             -2.155097   
1456             -0.091035             -0.126513             -2.155097   
1457             -0.091035             -0.126513              0.463857   
1458             -0.091035             -0.126513              0.463857   

      SaleCondition_Partial  SaleCondition_nan  
0                 -0.302641                0.0  
1                 -0.302641                0.0  
2                 -0.302641                0.0  
3                 -0.302641                0.0  
4            

In [17]:
# `Dummy_na=True` 将“na”（缺失值）视为有效的特征值，并为其创建指示符特征。
all_features = pd.get_dummies(all_features, dummy_na=True)
all_features.shape

(2919, 331)

In [19]:
n_train = train_data.shape[0]
train_features = torch.tensor(all_features[:n_train].values,
                              dtype=torch.float32)
test_features = torch.tensor(all_features[n_train:].values,
                             dtype=torch.float32)
train_labels = torch.tensor(train_data.SalePrice.values.reshape(-1, 1),
                            dtype=torch.float32)
train_features

tensor([[ 0.0673, -0.2020, -0.2178,  ...,  0.4639, -0.3026,  0.0000],
        [-0.8735,  0.5018, -0.0720,  ...,  0.4639, -0.3026,  0.0000],
        [ 0.0673, -0.0613,  0.1372,  ...,  0.4639, -0.3026,  0.0000],
        ...,
        [ 0.3025, -0.1551, -0.1428,  ...,  0.4639, -0.3026,  0.0000],
        [-0.8735, -0.0613, -0.0572,  ...,  0.4639, -0.3026,  0.0000],
        [-0.8735,  0.2672, -0.0293,  ...,  0.4639, -0.3026,  0.0000]])